### PR TITLE
First pass at how to contribute blog posts

### PR DESCRIPTION
**Pull request by svpernova09**
This is regarding #63

### CODE REVIEW

**Comment by unstablereality** [comment]
This guy is terrible and shouldn't be allowed to write code

**Comment by svpernova09** [comment]
> This guy is terrible and shouldn't be allowed to write code

You're not wrong.

**Comment by tbrownaw** [comment]
This doesn't say much about *what* front matter is appropriate.

**Comment by svpernova09** [comment]
Users should copy front matter from other files (i'm live coding this please have mercy)

**Pull request merged**
